apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yvmr-33/auto-rollback
    targetRevision: test/minikube_deploy
    path: charts/argo-cd
    helm:
      releaseName: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true