# 1. Active Service (Stable Traffic)
apiVersion: v1
kind: Service
metadata:
  name: auto-rollback-stable 
  namespace: auto-rollback-ns 
  labels:
    app: auto-rollback
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: auto-rollback 

---
# 2. Preview Service (Canary Traffic)
apiVersion: v1
kind: Service
metadata:
  name: auto-rollback-canary
  namespace: auto-rollback-ns
  labels:
    app: auto-rollback
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: auto-rollback 